version: "3.9"

services:
  backend:
    build: .
    container_name: cooking_assistant_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app       # <--- quan trọng: tự động cập nhật code
    environment:
      - PYTHONUNBUFFERED=1
